/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hmclrandombackgroundforward;

import java.io.IOException;
import hmclrandombackgroundforward.Shulker.colorANSI;

public class App {
    public static final String VERSION = "1.0.0";
    public String getGreeting() throws IOException {
        colorANSI color = new colorANSI();
        return color.color("cyan")+Server.getInstance().getConfig("operator")+color.color("green")+" "+"Random Background Image Forward Server"+color.color("reset");
    }
    public static void main(String[] args) throws IOException {
        colorANSI color = new colorANSI();
        System.out.println(new App().getGreeting());
        int status = Server.getInstance().runServer();
        if(status == 0){
            String port = Server.getInstance().getConfig("port");
            System.out.println(color.color("green")+"Service listen on port: "+color.color("yellow")+port+color.color("reset"));
        }else {
            System.out.println(color.color("red")+"Error: Status "+color.color("purple")+status);
        }

    }
}
